language: python
python:
- 3.6
- 3.5
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: willsheffler
  password:
    secure: iDikeKmWGKtgZz8D1w6cAfXea2w4QBJUNxOhdXCKU9D3ajeZiUCNp6tf9ewv2OHBxTqLkVewRydmVKC0kK0J60A2hVooPEir7XWQJheA2T6/Ddd2E3M4KOD35aplJoyTnhpLGI9+2NwLHhUwnGOZoxFgxKDazQwYk6akfw0zYcA1OjlrmStzIMdugJAOxfZxkNeQf5Fn8zahifUdhca7AbmtGqNAyRrTxMbm/7ZCO9BzwKjjw4ZHofDumYs3mATQduAcI4+cWkZPvxWQ93ynka82IMdtsB7qHkFnUEvBAZCZ6KR5aprWZNnl3CBKOHnJWqiQRAeFoZU4+BsCekJPEgT6RNHB4H2eVLhVsU1jk/QYO7R+GNG3r7f/BDrlGBLS6qCQo4mMyw+so89i8AfjrKyO88Zx6Mg6jyrJJQ0vMidSIqqJPsKgCzzVBWYoaDkwbLyxFkdPsU9MxiYfCpFI2dZDLmF/HBv88V/GJlfXK37Ex9jMYZDR6sXNVszo303e/xkRN+YPXsWcuDdbP51N08AcS3tBYve+OlOxmYQk4pU87PgdN+ynBIqcXOfodJGpziNZe9Tt2OMV4xwsIQYSJx1s9CIB6C9oZVQOBp/KMSdc4k6wQQk4JXweMrfwQhkM1YhrY61z6EQPd2UEaopzcE3uWE4hEJ4j6G0p+KLJXNE=
  on:
    tags: true
    repo: willsheffler/xbin
    python: 3.6
